AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
Metrics/LineLength:
  Max: 199

Style/UnneededPercentQ:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Documentation:
  Enabled: false