# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ed6bcea3b85b452fa9655fb8afb51837747a01520cc3e2de3056c470f29084ceda1ce47f5e5990f396019955de729317d412868a2c95c1a893daf690e253e45
  facebook_app_id: 899567300165649
  facebook_app_secret: f737b8743691c1e5b08d04dd5b831a03

test:
  secret_key_base: 8968a8f01c5681fdc186cef9dbee9aa8dd76a2806f59c3553247c982505b90158834359167fa99da65590203f54265a92034dc83b56e5e63857809d36238baac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
