test:
  mysql41: 9307
production:
  pid_file: /home/deployer/stackofw//shared/tmp/searchd.pid
  indices_location: /home/deployer/stackofw/shared/db/sphinx
  configuration_file: /home/deployer/stackofw/shared/config/production.sphinx.conf
  binlog_path: /home/deployer/stackofw/shared/binlog